"""
AI Decision ORM Model capturing multi-agent rationales and SHAP values for full explainability.
"""

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any
from sqlalchemy import (
    String,
    Float,
    Integer,
    DateTime,
    Text,
    ForeignKey,
    Index,
    JSON,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base

if TYPE_CHECKING:
    from app.models.block_plan import BlockPlan


class AIDecision(Base):
    """
    Detailed decision trace generated by specialized agents:
    - IngestionAgent: Feed validation & telemetry parsing
    - PriorityAgent: Machine learning score with feature importance & SHAP attributions
    - FusionAgent: Graph-based clustering rationale for multi-department co-location
    - OptimizerAgent: Pareto objective values (delay min, safety max, throughput max)
    - GuardianAgent: Safety envelope checks and conflict avoidance verifications
    - ExplainerAgent: Plain-language operational narrative for Railway Controllers
    """

    __tablename__ = "ai_decisions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    plan_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("block_plans.id", ondelete="CASCADE"), index=True, nullable=False
    )
    agent_name: Mapped[str] = mapped_column(
        String(64), index=True, nullable=False
    )  # e.g., "PriorityAgent", "OptimizerAgent"
    decision_json: Mapped[dict[str, Any]] = mapped_column(
        JSON, default=dict, nullable=False
    )  # Parameters, trade-offs, constraints satisfied
    explanation_text: Mapped[str] = mapped_column(Text, nullable=False)
    shap_values_json: Mapped[dict[str, Any]] = mapped_column(
        JSON, default=dict, nullable=False
    )  # Local feature attributions (traffic_density, overdue_days, severity)
    confidence: Mapped[float] = mapped_column(
        Float, default=0.95, nullable=False
    )  # 0.0 to 1.0
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        index=True,
        nullable=False,
    )

    # Relationships
    block_plan: Mapped["BlockPlan"] = relationship(
        "BlockPlan", back_populates="ai_decisions"
    )

    __table_args__ = (
        Index("ix_ai_decisions_agent_confidence", "agent_name", "confidence"),
    )

    def __repr__(self) -> str:
        return f"<AIDecision(agent='{self.agent_name}', plan_id={self.plan_id}, confidence={self.confidence:.2f})>"
